name: ai_doc
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  flutter_gemini: ^3.0.0
  chat_bubbles: ^1.7.0
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^11.4.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  provider: ^6.1.4
  intl: ^0.20.2
  uuid: ^4.5.1
  js: ^0.7.2
  agora_rtc_engine: ^6.5.1

  # Reminder section
  timezone: ^0.9.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
