// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrBcv4q_C3oCcyhzXSwzd32lJyN-VLZc',
    appId: '1:1008283635344:web:ed76ef39a842bb941c9215',
    messagingSenderId: '1008283635344',
    projectId: 'ai-d-fbad7',
    authDomain: 'ai-d-fbad7.firebaseapp.com',
    storageBucket: 'ai-d-fbad7.firebasestorage.app',
    measurementId: 'G-PCKNCH97RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJaRXje74mmuJbSjc96bMxgbqnr1-rC7Y',
    appId: '1:1008283635344:android:8509d33204767d981c9215',
    messagingSenderId: '1008283635344',
    projectId: 'ai-d-fbad7',
    storageBucket: 'ai-d-fbad7.firebasestorage.app',
  );
}
